name: Translate README

on:
  push:
    branches:
      - main
      - master
    paths:
      - "README.md"

permissions:
  contents: write
  pull-requests: write
  models: read

jobs:
  translate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ["spanish", "chinese"]
        include:
          - language: "spanish"
            file: "README.es.md"
          - language: "chinese"
            file: "README.zh.md"

    steps:
      - uses: actions/checkout@v5

      - name: Translate README
        uses: actions/ai-inference@v2
        id: translate
        with:
          max-tokens: 2000
          system-prompt: |
            You are a highly skilled ${{ matrix.language }} translator.

            ## Your Responsibilities

            - Translate the provided text to ${{ matrix.language }}
            - Detect the source language automatically
            - Return only the translation, no explanations or notes

            ## Input

            You will receive the text to translate in the user message.

            ## Translation Rules
            - Preserve the meaning, tone, formatting, structure, and style of the original text
            - Keep technical terms, code blocks, and code examples in their original form
            - Keep URLs, file paths, and image references unchanged
                      
          prompt-file: README.md


      - name: Save translation
        run: |
          mkdir -p docs
          echo "$TRANSLATED_TEXT" | tee docs/${{ matrix.file }}
        env:
          TRANSLATED_TEXT: ${{ steps.translate.outputs.response }}

      - name: Upload translation artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file }}
          path: docs/${{ matrix.file }}

  create-pr:
    needs: translate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v4
        with:
          path: docs
          merge-multiple: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "docs: update translations of README"
          title: "docs: update translations of README"
          body: |
            This PR updates all translations of the README:

            Changes were automatically generated using the [ai-inference](https://github.com/actions/ai-inference) action.
          branch: docs/update-readme-translations
          add-paths: "docs/README*"
          delete-branch: true
          labels: |
            documentation